### ISSUE TITLE
Additional info may be useful for the event summary.

### ISSUE THREAD

**Issue by ChristyGHanson** [caseyfee/FetchYaPet#49]
For now, I can see the following:

1. Event Name
2. Date
3. Time
4. Location

![location-event](https://user-images.githubusercontent.com/34938344/219113744-cbc83dc4-bac5-4b5a-86b7-f4cebb50a962.png)

Some additional info in the above event sneak peek could further user interests/usability.

- City, State (Only I would I know where Popejoy Hall is, but that's because I'm familiar with the location.)
- Distance in miles as a default for now.

**Comment by Bryan-Codes** [comment]
City and state are displayed on the Bing map
