### ISSUE TITLE
Issue: The events are loaded, but new events will not populate upon a new search

### ISSUE THREAD

**Issue by ChristyGHanson** [caseyfee/FetchYaPet#50]
The events are loaded, but new events will not populate upon a new search. This could be because no events are available for me to attend within less than 100 miles with the TicketMaster API. It will populate a Telluride event in CO, which is much farther than 100 mile radius and also events in Albuquerque that are at least 230 miles from me.

![event-dash-search](https://user-images.githubusercontent.com/34938344/219117569-23225eb0-c12c-47fe-8ba3-a32c606bec35.png)

Solution for future development:

Add a message that prints to the user on the screen. 
"No events available in your selected area. Try increasing the radius."

![no-events-available-in-your-selected-area](https://user-images.githubusercontent.com/34938344/219117411-75cf500f-a7d9-4a05-9557-c14227a23151.png)

**Comment by ChristyGHanson** [comment]
This could fall under the criterion: "Be interactive (accept and respond to user input."

**Comment by Bryan-Codes** [comment]
Won't fix
