### ISSUE TITLE
Issue: I typed in a string. No results returned.

### ISSUE THREAD

**Issue by ChristyGHanson** [caseyfee/FetchYaPet#51]
What should happen if a user types in a string in the search box?

Solution: We could return a result that reads "Please type in a number."

![string-not-an-int](https://user-images.githubusercontent.com/34938344/219118699-f88250d1-0155-449f-bb72-33ff47349e62.png)

**Comment by ChristyGHanson** [comment]
This could be something we can consider to hit on this project criterion: "Be interactive (accept and respond to user input."

**Comment by Bryan-Codes** [comment]
Won't Fix
